# Generated by Django 2.2 on 2019-04-02 00:59

from django.db import migrations



def delete_permission_action_point(apps, schema_editor, reverse=False):
    """
    Update the content_type of proxy model permissions to use the ContentType
    of the proxy model.
    """
    Permission = apps.get_model('auth', 'Permission')
    ActionPoint = apps.get_model('action_points', 'ActionPoint')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    concrete_content_type = ContentType.objects.get_for_model(ActionPoint, for_concrete_model=True)
    Permission.objects.filter(content_type=concrete_content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('action_points', '0008_auto_20180731_1050'),
        ('auth', '0010_alter_group_name_max_length'),
    ]

    operations = [
        migrations.RunPython(delete_permission_action_point, ),
    ]
